Run Firefox on remote server through X11. Start works fine but see that webint output is delayed compared to browser, in a while webint output freezes and firefox unexpectedly quits.

diff --git a/installKP b/installKP
--- a/installKP
+++ b/installKP
@@ -10,38 +10,25 @@ if [[ $# < 1 ]]; then
 	exit 0
 fi
 
-ssh $1 hostname 2>/dev/null
-if [[ $? -ne 0 ]]; then
-	echo "Cannot connect with ssh $1."
-	exit 1
-fi
+REMOTE=$1
+
+ssh $REMOTE hostname 2>/dev/null || (echo "Cannot connect with 'SSH $REMOTE'." && exit 1)
+
 
 SSH_OPTIONS="-o ServerAliveInterval=15"
+SSH_X_OPTIONS="-X"
 
 # Copy files to remote
 echo "Synchronising installation files with remote location."
-./sync_up.sh $1 -do
+./sync_up.sh $REMOTE -do
 
 echo "Starting remote installation web-server."
 
-
-ssh $1 $SSH_OPTIONS kportal/start.sh
-
-#echo "Starting remote installation web-server."
-#ssh $1 'nohup $HOME/kportal/webint/webint.py </dev/null &'
-#echo "Creating SSH tunnel"
-#LOCAL_PORT=5000
-#ssh -L $LOCAL_PORT:localhost:8080 $1 -f -N
-#echo "Opening web address in browser."
-#xdg-open &>/dev/null
-#if [[ $? -ne 0 ]]; then
-#	open http://localhost:$LOCAL_PORT
-#else
-#	xdg-open http://localhost:$LOCAL_PORT	
-#fi
-#
-#if [[ $? -ne 0 ]]; then
-#	echo "Open the following address in your Internet browser to continue installation:"
-#	echo "http://localhost:$LOCAL_PORT"
-#fi
+ssh $REMOTE $SSH_OPTIONS kportal/install_required_ubuntu.sh
+# Kill webint server if its already running
+ssh $REMOTE $SSH_OPTIONS "PID=\$(sudo lsof -i -n -P | grep '*:8080 (LISTEN)' | awk '{ print \$2 }' | head -1) &&sudo kill \$PID" || true
+echo "Open browser"
+ssh $REMOTE $SSH_OPTIONS $SSH_X_OPTIONS 'nohup kportal/start.sh localhost </dev/null' &
+echo "Start server"
+ssh $REMOTE $SSH_OPTIONS kportal/start_webint_server.sh
 
